// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_http_client

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClientInf creates a new instance of MockClientInf. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientInf(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientInf {
	mock := &MockClientInf{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientInf is an autogenerated mock type for the ClientInf type
type MockClientInf struct {
	mock.Mock
}

type MockClientInf_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientInf) EXPECT() *MockClientInf_Expecter {
	return &MockClientInf_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockClientInf
func (_mock *MockClientInf) Get(ctx context.Context, url string) ([]byte, error) {
	ret := _mock.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, url)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientInf_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockClientInf_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockClientInf_Expecter) Get(ctx interface{}, url interface{}) *MockClientInf_Get_Call {
	return &MockClientInf_Get_Call{Call: _e.mock.On("Get", ctx, url)}
}

func (_c *MockClientInf_Get_Call) Run(run func(ctx context.Context, url string)) *MockClientInf_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientInf_Get_Call) Return(bytes []byte, err error) *MockClientInf_Get_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockClientInf_Get_Call) RunAndReturn(run func(ctx context.Context, url string) ([]byte, error)) *MockClientInf_Get_Call {
	_c.Call.Return(run)
	return _c
}
